[package]
name = "storable-api"
version = "0.1.0"
edition = "2021"
description = "HTTP API server for Storable"
license = "MIT"

[dependencies]
axum = "0.8.8"
tokio = { version = "1", features = ["full"] }
storable-core = { path = "../storable-core" }
storable-db   = { path = "../storable-db" }
